(global-set-key [mouse-3] 'mouse-popup-menubar-stuff)
(global-set-key (kbd "C-<mouse-5>") 'text-scale-decrease)
(global-set-key (kbd "C-<mouse-4>") 'text-scale-increase)
(global-set-key [C-down-mouse-3] 'yank)
(global-set-key (kbd "C-²") 'other-frame)
(global-set-key (kbd "C-h") 'windmove-left)
(global-set-key (kbd "C-j") 'windmove-down)
(global-set-key (kbd "C-l") 'windmove-right)
(global-set-key (kbd "C-k") 'windmove-up)
(global-set-key (kbd "M-,") 'kill-buffer-and-window)
(global-set-key (kbd "C-!") 'eshell-toggle)
(global-set-key (kbd "C-:") 'company-complete)
(global-set-key (kbd "C-<tab>") 'buffer-expose-project)
(global-set-key (kbd "C-M-<left>") 'winner-undo)
(global-set-key (kbd "C-M-<right>") 'winner-redo)
(global-set-key (kbd "M-=") 'er/contract-region)
(global-set-key (kbd "C-S-f") 'helm-projectile-ag)
