(global-set-key [mouse-3] 'mouse-popup-menubar-stuff)
(global-set-key (kbd "C-<mouse-5>") 'text-scale-decrease)
(global-set-key (kbd "C-<mouse-4>") 'text-scale-increase)
(global-set-key [C-down-mouse-3] 'yank)
(global-set-key (kbd "C-²") 'other-frame)
(global-set-key (kbd "C-h") 'windmove-left)
(global-set-key (kbd "C-j") 'windmove-down)
(global-set-key (kbd "C-l") 'windmove-right)
(global-set-key (kbd "C-k") 'windmove-up)
(global-set-key (kbd "M-,") 'kill-buffer-and-window)
(global-set-key (kbd "C-!") 'eshell-here)
(global-set-key (kbd "C-:") 'company-complete)
(global-set-key (kbd "C-<tab>") 'helm-mini)
(global-set-key (kbd "M-i") 'company-capf)
(global-set-key (kbd "<f9>") 'zeal-at-point-search)
(global-set-key (kbd "C-M-<left>") 'winner-undo)
(global-set-key (kbd "C-M-<right>") 'winner-redo)
(global-set-key (kbd "s-<prior>") 'previous-buffer)
(global-set-key (kbd "s-<next>") 'next-buffer)
(global-set-key (kbd "M-=") 'er/contract-region)


;; LEADER KEYS
(progn
  ;; define a prefix keymap
  (define-prefix-command 'bb-mod-key-map)
  (define-key bb-mod-key-map "c" 'org-capture)
  (define-key bb-mod-key-map "C" 'bb/tear-off-window)
  (define-key bb-mod-key-map "b" 'helm-buffers-list)
  (define-key bb-mod-key-map "!" 'ansi-term)
  (define-key bb-mod-key-map (kbd "<SPC>") 'helm-all-mark-rings)
  (define-key bb-mod-key-map (kbd "<f2>") 'helm-bookmarks)
  (define-key bb-mod-key-map (kbd "M-x") 'helm-M-x)
  (define-key bb-mod-key-map "s" 'crux-create-scratch-buffer)
  (define-key bb-mod-key-map "-" 'helm-find-files)
  (define-key bb-mod-key-map "a" 'helm-do-ag)
  (define-key bb-mod-key-map "A" 'org-agenda)
  (define-key bb-mod-key-map "r" 'helm-recentf)
  (define-key bb-mod-key-map "+" 'calc)
  (define-key bb-mod-key-map "l" 'helm-locate)
  (define-key bb-mod-key-map "g" 'helm-do-grep-ag)
  (define-key bb-mod-key-map "t" 'treemacs)
  (define-key bb-mod-key-map "n" 'deft-new-file)
  (define-key bb-mod-key-map "o" 'helm-occur)
  (define-key bb-mod-key-map "u" 'undo-tree-visualize)
  (define-key bb-mod-key-map "h" 'helm-dash-at-point)
  (define-key bb-mod-key-map "m" 'magit-status)
  (define-key bb-mod-key-map (kbd "<RET>") 'terminal-here)
  (define-key bb-mod-key-map (kbd "<f11>") 'helm-resume)
  (define-key bb-mod-key-map (kbd "<f12>") 'modifier-one)
  (define-key bb-mod-key-map "p" 'helm-show-kill-ring))
(global-set-key (kbd "<f12>") bb-mod-key-map)

(progn
  ;; define a prefix keymap
  (define-prefix-command 'modifier-one)
  (define-key modifier-one (kbd "o") 'find-other-file-other-window)
  (define-key modifier-one (kbd "!") 'eshell-here)
  (define-key modifier-one (kbd "e") 'eshell-other-window)
  (define-key modifier-one (kbd "d") 'pdb_at_point)
  (define-key modifier-one (kbd "g") 'thunar))
(progn
  ;; define a prefix keymap
  (define-prefix-command 'modifier-two)
  (define-key modifier-two (kbd "q") 'imenu-list-smart-toggle)
  (define-key modifier-two (kbd "m") 'toggle-truncate-lines)
  (define-key modifier-two (kbd "!") 'eshell-here)
  (define-key modifier-two (kbd "m") 'menu-bar-mode))
